name: Publish project website

on:
  push:
    branches: [ trunk, docs ]

jobs:
  deploy-website:
    name: Deploy mkdocs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        with:
          lfs: true
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: .github/workflows/mkdocs_requirements.txt
          EXTRA_PACKAGES: git-lfs
